openapi: 3.0.0
info:
  title: KALVI Platform API
  version: 1.0.0
  description: API documentation for the KALVI Platform

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

paths:
  /api/courses:
    post:
      summary: Get all available courses
      security:
        - basicAuth: []
      responses:
        200:
          description: OK
